BASE_URL = 'https://archive.ics.uci.edu/ml/machine-learning-databases/optdigits'.freeze

task default: %w[
  optdigits-cv.json optdigits-tra.json optdigits-wdep.json optdigits-windep.json
]

file 'optdigits-cv.json' => 'optdigits-orig.cv' do
  ruby 'cook-optdigits.rb optdigits-orig.cv > optdigits-cv.json'
end

file 'optdigits-tra.json' => 'optdigits-orig.tra' do
  ruby 'cook-optdigits.rb optdigits-orig.tra > optdigits-tra.json'
end

file 'optdigits-wdep.json' => 'optdigits-orig.wdep' do
  ruby 'cook-optdigits.rb optdigits-orig.wdep > optdigits-wdep.json'
end

file 'optdigits-windep.json' => 'optdigits-orig.windep' do
  ruby 'cook-optdigits.rb optdigits-orig.windep > optdigits-windep.json'
end

file 'optdigits-orig.cv' do
  system "curl #{BASE_URL}/optdigits-orig.cv.Z | uncompress -c > optdigits-orig.cv"
end

file 'optdigits-orig.tra' do
  system "curl #{BASE_URL}/optdigits-orig.tra.Z | uncompress -c > optdigits-orig.tra"
end

file 'optdigits-orig.wdep' do
  system "curl #{BASE_URL}/optdigits-orig.wdep.Z | uncompress -c > optdigits-orig.wdep"
end

file 'optdigits-orig.windep' do
  system "curl #{BASE_URL}/optdigits-orig.windep.Z | uncompress -c > optdigits-orig.windep"
end

task :clean do
  system 'rm *.json'
end

task :realclean do
  system 'rm *.json optdigits-orig.*'
end
